//Script to plot histograms generated by ZTauTauHistMaker
#include "../rootScripts/DataPlotter.cc+g"

namespace {
  DataPlotter* dataplotter_ = 0;
}

int initialize_data(TString selection = "emu") {
  dataplotter_ = new DataPlotter();
  dataplotter_->set_luminosity(35.9e3); //luminosity in pb^-1
  dataplotter_->plot_data_ = 0;
  dataplotter_->folder_ = "example";
  dataplotter_->rebinH_ = 5;
  dataplotter_->doStatsLegend_ = 0;
  dataplotter_->include_qcd_ = 0;
  dataplotter_->draw_statistics_ = false;
  int status = 0;
  status += dataplotter_->add_dataset(Form("ztautau_%s_bltTree_zemu.hist"          , selection.Data()), "bltTree_zemu", "Z->e#mu"    , false, 0.028, true);
  status += dataplotter_->add_dataset(Form("ztautau_%s_bltTree_hemu.hist"          , selection.Data()), "bltTree_hemu", "H->e#mu"    , false, 0.015, true);
  status += dataplotter_->add_dataset(Form("ztautau_%s_bltTree_htautau_gluglu.hist", selection.Data()), "bltTree_zemu", "H->#tau#tau", false, 3.07 , false);
  status += dataplotter_->add_dataset(Form("ztautau_%s_bltTree_t_tw.hist"          , selection.Data()), "bltTree_zemu", "Top"        , false, 35.85, false);
  status += dataplotter_->add_dataset(Form("ztautau_%s_bltTree_tbar_tw.hist"       , selection.Data()), "bltTree_zemu", "Top"        , false, 35.85, false);
  dataplotter_->init_files();
  return status;
}

TCanvas* plot_histograms(TString hist = "lepm", int set = 48, TString selection = "emu", TString type = "event",
			 double xmin = 1., double xmax = -1., int rebin = 5) {
  if(dataplotter_ == 0) initialize_data();
  TCanvas* c = dataplotter_->plot_stack(DataPlotter::PlottingCard_t(hist, type, set, rebin, xmin, xmax));
  return c;
}
