//Script to plot histograms generated by ZTauTauHistMaker
#include "../rootScripts/DataPlotter.cc+g"

namespace {
  DataPlotter* dataplotter_ = 0;
}

int initialize_data(TString selection = "emu") {
  dataplotter_ = new DataPlotter();
  dataplotter_->set_luminosity(35.9e3); //luminosity in pb^-1
  dataplotter_->plot_data_ = 0;
  dataplotter_->folder_ = "example";
  dataplotter_->rebinH_ = 5;
  dataplotter_->doStatsLegend_ = 0;
  dataplotter_->include_qcd_ = 0;
  dataplotter_->draw_statistics_ = false;
  //for simplicity
  typedef DataPlotter::DataCard_t datacard;
  std::vector<datacard> cards;
  //card constructor: filename, tree name, dataset label, isData, xsec, isSignal, color
  cards.push_back(datacard(("ztautau_"+selection+"_bltTree_zemu.hist"          ).Data(), "bltTree_zemu"          , "Z->e#mu"    , false, 0.028, true , kBlue));
  cards.push_back(datacard(("ztautau_"+selection+"_bltTree_hemu.hist"          ).Data(), "bltTree_hemu"          , "H->e#mu"    , false, 0.015, true , kOrange));
  cards.push_back(datacard(("ztautau_"+selection+"_bltTree_htautau_gluglu.hist").Data(), "bltTree_htautau_gluglu", "H->#tau#tau", false, 3.07 , false, kViolet-3));
  cards.push_back(datacard(("ztautau_"+selection+"_bltTree_t_tw.hist"          ).Data(), "bltTree_t_tw"          , "Top"        , false, 35.85, false, kYellow-7));
  cards.push_back(datacard(("ztautau_"+selection+"_bltTree_tbar_tw.hist"       ).Data(), "bltTree_tbar_tw"       , "Top"        , false, 35.85, false, kYellow-7));
  int status = 0;
  for(datacard card : cards)
    status += dataplotter_->add_dataset(card);
  dataplotter_->init_files();
  return status;
}

TCanvas* plot_histograms(TString hist = "lepm", int set = 48, TString selection = "emu", TString type = "event",
			 double xmin = 1., double xmax = -1., int rebin = 5) {
  if(dataplotter_ == 0) initialize_data();
  TCanvas* c = dataplotter_->plot_stack(DataPlotter::PlottingCard_t(hist, type, set, rebin, xmin, xmax));
  return c;
}
