#include <vector>
#include <map>
#include <utility>
#include <string>

#include "interface/GlobalConstants.h"
#include "interface/Tree_t.hh"
#include "interface/EventHist_t.hh"
#include "interface/LepHist_t.hh"
#include "interface/SystematicHist_t.hh"
#include "interface/CrossSections.hh"
#include "interface/Significances.hh"
#include "interface/Utilities.hh"
#include "interface/CreateCategories.hh"
#include "interface/BTagWeight.hh"
#include "interface/PUWeight.hh"
#include "interface/JetPUWeight.hh"
#include "interface/PrefireWeight.hh"
#include "interface/JetToLepWeight.hh"
#include "interface/JetToTauWeight.hh"
#include "interface/JetToTauComposition.hh"
#include "interface/QCDWeight.hh"
#include "interface/MuonIDWeight.hh"
#include "interface/ZPtWeight.hh"
#include "interface/EmbeddingWeight.hh"
#include "interface/EmbeddingTnPWeight.hh"
#include "interface/TauIDWeight.hh"
#include "interface/ElectronIDWeight.hh"
#include "interface/SlimObject_t.hh"
#include "interface/SlimElectron_t.hh"
#include "interface/SlimMuon_t.hh"
#include "interface/SlimTau_t.hh"
#include "interface/SlimJet_t.hh"
#include "interface/SlimPhoton_t.hh"
#include "interface/RoccoR.h"
#include "interface/MVAConfig.hh"
#include "interface/TrkQualInit.hh"
#include "interface/ZTauTauHistMaker.hh"
#include "interface/DataCard_t.hh"
#include "interface/PlottingCard_t.hh"
#include "interface/DataPlotter.hh"
#include "interface/ParticleCorrections.hh"
#include "interface/NanoAODConversion.hh"
#include "interface/Fitter.hh"

using namespace CLFV;
namespace CLFV {
  struct dictionary {
    Tree_t dummy1;
    EventHist_t dummy1b;
    LepHist_t dummy1c;
    SystematicHist_t dummy1d;
    CrossSections dummy2;
    Significances dummy3;
    Utilities dummy3a;
    CreateCategories dummy3b;
    BTagWeight dummy4;
    PUWeight dummy5;
    JetPUWeight dummy5b;
    PrefireWeight dummy5c;
    JetToTauWeight dummy6;
    JetToTauComposition dummy6b;
    JetToLepWeight dummy6b2;
    QCDWeight dummy6b3;
    ElectronIDWeight dummy6c2;
    MuonIDWeight dummy6c;
    TauIDWeight dummy6d;
    ZPtWeight dummy6e;
    EmbeddingWeight dummy6f;
    EmbeddingTnPWeight dummy6f2;
    SlimObject_t dummy7;
    SlimElectron_t dummy8;
    SlimMuon_t dummy9;
    SlimTau_t dummy10;
    SlimJet_t dummy11;
    SlimPhoton_t dummy12;
    RoccoR dummy12b;
    MVAConfig dummy13;
    TrkQualInit dummy14;
    ZTauTauHistMaker dummy15;
    DataCard_t dummy15b;
    PlottingCard_t dummy15c;
    DataPlotter dummy16;
    ParticleCorrections dummy17;
    NanoAODConversion dummy18;
    Fitter dummy19;
  };
}
