#include <vector>
#include <map>
#include <utility>
#include <string>
#include "interface/Tree_t.hh"
#include "interface/EventHist_t.hh"
#include "interface/LepHist_t.hh"
#include "interface/SystematicHist_t.hh"
#include "interface/CrossSections.hh"
#include "interface/Significances.hh"
#include "interface/CreateCategories.hh"
#include "interface/BTagWeight.hh"
#include "interface/PUWeight.hh"
#include "interface/JetPUWeight.hh"
#include "interface/PrefireWeight.hh"
#include "interface/JetToTauWeight.hh"
#include "interface/JetToTauComposition.hh"
#include "interface/QCDWeight.hh"
#include "interface/MuonIDWeight.hh"
#include "interface/ElectronIDWeight.hh"
#include "interface/SlimObject_t.hh"
#include "interface/SlimElectron_t.hh"
#include "interface/SlimMuon_t.hh"
#include "interface/SlimTau_t.hh"
#include "interface/SlimJet_t.hh"
#include "interface/SlimPhoton_t.hh"
#include "interface/RoccoR.h"
#include "interface/MVAConfig.hh"
#include "interface/TrkQualInit.hh"
#include "interface/PlottingCard_t.hh"
#include "interface/DataCard_t.hh"
#include "interface/ZTauTauHistMaker.hh"
#include "interface/DataPlotter.hh"
#include "interface/StandardDataConfig.hh"
#include "interface/ParticleCorrections.hh"
#include "interface/NanoAODConversion.hh"

namespace { struct dictionary {
  Tree_t dummy1;
  CrossSections dummy2;
  Significances dummy3;
  CreateCategories dummy3b;
  BTagWeight dummy4;
  PUWeight dummy5;
  JetPUWeight dummy5b;
  PrefireWeight dummy5c;
  JetToTauWeight dummy6;
  JetToTauComposition dummy6b;
  QCDWeight dummy6bb;
  MuonIDWeight dummy6c;
  ZPtWeight dummy6d;
  SlimObject_t dummy7;
  SlimElectron_t dummy8;
  SlimMuon_t dummy9;
  SlimTau_t dummy10;
  SlimJet_t dummy11;
  SlimPhoton_t dummy12;
  RoccoR dummy12b;
  MVAConfig dummy13;
  TrkQualInit dummy14;
  ZTauTauHistMaker dummy15;
  DataPlotter dummy16;
  ParticleCorrections dummy17;
  NanoAODConversion dummy18;
};
}
